### PR TITLE
Check for calloc() failure in filesystem code

### PR DESCRIPTION
**Pull request by scaprile**
closes #2170

### CODE REVIEW

**Comment by akulpillai** [comment]
Hi! I’m a student researcher working with @szsam. We have identified this patch as one for a security vulnerability. 

Will a CVE be issued for this?

**Comment by scaprile** [comment]
@akulpillai Security issues shall be discussed with support@cesanta.com . Thank you

**Comment by Machiry** [comment]
Hey @scaprile,

I am Aravind Machiry, an Assistant Professor at Purdue's ECE Department.

This pull request (along with several others) is the result of our ongoing research work (along with @szsam) to improve the security of open-source embedded projects.

We are doing a short (5-minute) survey to understand the use of static analysis tools in embedded projects.

It would greatly benefit our research if you could fill out this anonymous survey: https://purdue.ca1.qualtrics.com/jfe/form/SV_0OnXfr5plPe1QCa

Thank you,
Aravind

**Comment by cpq** [comment]
@akulpillai , usually it is the security group that finds a vulnerability, publishes a CVE. Not us. We're a vendor. Our job is to fix the vulnerability, not publish CVEs.

The usual practice is that a security group notifies us in private PRIOR to any public announcement, or patches, or issues. Then we make a fix and allow our customers to update, usually it takes a month. Only AFTER that a security group publishes a CVE.

Does that answer your question about the CVE?

**Pull request merged**
