### PR TITLE
FreeRTOS requires a valid proto arg to socket()

### PR DESCRIPTION
**Pull request by quartzjer**
Simple fix.

### CODE REVIEW

**Comment by scaprile** [comment]
Can you please explain why and where is this needed ? We build every day for FreeRTOS and don't need anything extra.

**Comment by quartzjer** [comment]
It builds fine without this, the problem we encountered is when you pass `0` into FreeRTOS's `socket()` wrapper, at runtime it returns an error and fails.

It hits this assert with a zero value passed in: https://github.com/particle-iot/freertos/blob/1f3aae61b26354cbf38e87b36994e2a4b78d7593/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/FreeRTOS_Sockets.c#L255

**Comment by cpq** [comment]
Ah. It's FreeRTOS+TCP , being BSD socket compatible but not su much. This change looks good to me
thank you @quartzjer

**Comment by scaprile** [comment]
@cpq I plan to test on Monday and also change other two calls to socket(), so the OP wouldn't need to sign the CLA. WDYT ?

**Comment by quartzjer** [comment]
Sorry I didn't get the CLA signed in time, but very glad to hear you got the fix incorporated regardless, thanks!

**Comment by scaprile** [comment]
We didn't actually did exactly what you submitted, so no CLA was necessary as we didn't include your code.

**Pull request closed without merging**
