### PR TITLE
Reintroduce missing HTTP status code strings

### PR DESCRIPTION
**Pull request by james-advmach**
These were added in 1115514 in response to #1266 but were then removed in ef44f90.

There's nothing to suggest why they were removed in the commit message or the discussion around #1520. Perhaps they were removed by accident?

### CODE REVIEW

**Comment by cpq** [comment]
Closing this.
Appreciate your attention!
If you have a specific code(s) that you need covered in your product, please file a PR. That would be compelling enough to get into the mainstream.

**Comment by scaprile** [comment]
> the reason they were removed is that they are useless. Those codes that are used by the library already, are in.
> Can you provide a **compelling evidence / use case**, why codes e.g. `412 Precondition Failed` or `410 Gone` might be required?

Why ? In which case ? Because of what ? What is the use case for it ?

> If we call `mg_http_reply` with, say, status code 410 ("Gone"), then it'll reply to the client with the wrong string. It'll say `HTTP/1.1 410 OK`, which is not right!

If you nevertheless have/want to use one of those codes, use [mg_printf](https://mongoose.ws/documentation/#mg_printf-mg_vprintf) instead:
```
 mg_printf(c, "HTTP/1.1 410 Gone\r\nContent-length: 0\r\n\r\n");
```
Wireshark says:
```
Transmission Control Protocol, Src Port: 8000, Dst Port: 39962, Seq: 1, Ack: 449, Len: 40
Hypertext Transfer Protocol
    HTTP/1.1 410 Gone\r\n
    Content-length: 0\r\n
    \r\n
    [HTTP response 1/1]
```
Wouldn't that work for you in such a case ?

**Comment by scaprile** [comment]
That function does not return any value, here is the list of supported codes, you may add a 200 and change the default "OK" at your wish:
https://github.com/cesanta/mongoose/blob/5cebce3f4bf677727c1c2ee2db519c44a3452f42/src/http.c#L296-L315

**Comment by cpq** [comment]
@rgilton if you want to use rarely used reason strings for 410 and others, create your own utility function.

I dont really see the value in those reason strings, other than bloating the codebase.

**Comment by cpq** [comment]
@rgilton 

Reading https://datatracker.ietf.org/doc/html/rfc2616#section-6.1.1 

```
  The individual values of the numeric status codes defined for
   HTTP/1.1, and an example set of corresponding Reason-Phrase's, are
   presented below. The reason phrases listed here are only
   recommendations -- they MAY be replaced by local equivalents without
   affecting the protocol.
```

I read it as that the implementation (mongoose library) can use whatever reason phrase it pleases.

**Comment by cpq** [comment]
@rgilton that sounds reasonable! Can you elaborate on your use case please, how exactly reason phrases interfere with your  program logic? Do you fetch reason phrases from the HTTP responses - and if yes, why?

@scaprile could you add a note to the https://mongoose.ws/documentation/#mg_http_reply docs please, stating that only a subset of reason phrases are unique. With a permalink to the [github code ](https://github.com/cesanta/mongoose/blob/5cebce3f4bf677727c1c2ee2db519c44a3452f42/src/http.c#L296-L315)

**Pull request closed without merging**
