### PR TITLE
add conn_data to mg_connection

### PR DESCRIPTION
**Pull request by mzihlmann**
conn_data is a hook for the user to attach arbitrary data on the connection itself. this allows the user to manage arbitrary state on the connection without relying on an external database for a mapping id -> void*.

### CODE REVIEW

**Comment by cpq** [comment]
Use `fn_data`

Closing this.

**Comment by mzihlmann** [comment]
`fn_data` is a reference to an object on the listening connection. Assume i only have one listening socket, so for me `fn_data` is like a global value, all incoming connections reference the same copy. I cannot modify this **per-connection**, it would affect the state of all connections currently handled. I could replace it on a connection basis but then i also lose reference to it and abuse mongoose, of course it works, but its more simple and straightforward if mongoose would offer a possibility to have a unique userdata attached to each unique connection id. If i get it wrong please explain it to me, would be greatly appreciated.

**Comment by cpq** [comment]
You could modify it per connection, just set `c->fn_data` to a new value.

Let us explain that better in the docs, because it is not clear, and your confusion in genuine.

**Comment by cpq** [comment]
Updated https://github.com/cesanta/mongoose/tree/master/docs#event-handler-function

Thanks for your patience and for getting in touch! Let us know if it is still unclear.

**Pull request closed without merging**
