### PR TITLE
move static function mg_url_decode to header file

### PR DESCRIPTION
**Pull request by kazan417**
Somtimes we need to use this static function from other application.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/mongoose/596)

### CODE REVIEW

**Comment by kazan417** [comment]
move mg_url_decode to header file

**Comment by kazan417** [comment]
I am also trying to add travis ci and coverity scan integration, but i am not listed in contributors of main repo, because of it administration of this services does not approove my request

**Comment by kazan417** [comment]
move mg_url_decode to header file is bad idea, better to declare it as non static function in header.

**Comment by cpq** [comment]
Pushed https://github.com/cesanta/dev/pull/2045

**Pull request closed without merging**
