### PR TITLE
Replace obsolete gethostbyname by getaddrinfo

### PR DESCRIPTION
**Pull request by CurlyMoo**
This also protect against the latest glibc bug

### CODE REVIEW

**Comment by cpq** [comment]
Thank you for the change!

`getaddrinfo` is not as portable as gethostbyname, for example MSVC6 doesn't have it.
Other OSes (especially embedded ones) might not have getaddrinfo as well.
Since this change doesn't provide a visible benefit over gethostbyname, and looses in portability, I tend to not to merge it.

**Comment by CurlyMoo** [comment]
I think the benefits are clear:
1. gethostbyname isn't thread safe.
2. gethostbyname isn't reentrant.
3. gethostbyname doesn't support ipv6.
4. gethostbyname is considered obsolete because all of the above.

So instead of just not including it you should opt for the alternative and that is to check if getaddrinfo is available and then use it, if not fallback to gethostbyname. For example, that's how PolarSSL ensures portability.

**Comment by cpq** [comment]
Makes sense. Please wrap your change into the `#ifdef NS_ENABLE_GETADDRINFO` conditional.

**Comment by CurlyMoo** [comment]
Done

**Comment by cpq** [comment]
Thank you. Please confirm that you're fine to release your change under the current mongoose license - then I'll merge it.

**Comment by CurlyMoo** [comment]
As long as it `also` stays Open Source GPLv2 i'm fine with it.

**Comment by cpq** [comment]
Merging, thank you.

**Pull request merged**
