### PR TITLE
Move docs to website

### PR DESCRIPTION
**Pull request by scaprile**

### CODE REVIEW

**Comment by Skinner927** [comment]
Are the docs available anywhere for download?

**Comment by scaprile** [comment]
At this moment the current markdown is not publicly available. There haven't been many changes since that commit, though. May I ask why you need to download the docs ?

**Comment by Skinner927** [comment]
For offline viewing/development.

This is currently the only alternative way I know how to view the docs offline:

```
wget --mirror --convert-links --adjust-extension --page-requisites --no-parent https://mongoose.ws/
```

**Comment by scaprile** [comment]
Besides downloading release 7.9, you can browse/checkout the repo at the commit just before this one:
https://github.com/cesanta/mongoose/tree/a0601f1/docs
I'll see what we can do for the future, we are in a process of restructuring documentation

**Pull request merged**
