### PR TITLE
Test with 4096 MG_MAX_RECV_BUF_SIZE

### PR DESCRIPTION
**Pull request by jameshilliard**
Expected to fail without #1476.

### CODE REVIEW

**Comment by cpq** [comment]
The 4096 ought to fail, because unit test fetched test/data/ca.pem which is ~30kb in size.
When I set MG_MAX_RECV_BUF_SIZE to 35000 or more, tests pass.

**Comment by jameshilliard** [comment]
> The 4096 ought to fail, because unit test fetched test/data/ca.pem which is ~30kb in size.

If you only process the data once fully received/buffered with `MG_EV_HTTP_MSG` yes that is true, but if using `MG_EV_HTTP_CHUNK` or something that drains the buffer when it hits `MG_MAX_RECV_BUF_SIZE` then it should not fail.

**Comment by cpq** [comment]
That's correct.

If we submit your change, then the behavior for use cases that do not process chunks (and that's the majority) will change. When a limit is hit, instead of failiing, the processing will just hang. Is that true?

**Comment by jameshilliard** [comment]
> If we submit your change, then the behavior for use cases that do not process chunks (and that's the majority) will change. 

Yeah, that's true, I made the retry behavior configurable in #1476 with the current behavior the default.

> When a limit is hit, instead of failiing, the processing will just hang. Is that true?

Depends if timeouts are implemented but yeah it would keep retrying.

**Comment by cpq** [comment]
Closing this, as it works as expected.

**Pull request closed without merging**
