### PR TITLE
deprecate mg_mkpipe()

### PR DESCRIPTION
**Pull request by scaprile**

### CODE REVIEW

**Review by cpq — APPROVED** [review]

**Comment by craigtao** [comment]
Deprecation of mg_mkpipe(), Is there an alternative function or others?  thanks

zaitao.huang Elekta

**Comment by scaprile** [comment]
@craigtao This is 1 year ago, please don't necropost. 
Please see our [documentation](https://mongoose.ws/documentation/),  and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).
https://mongoose.ws/documentation/tutorials/core/multi-threaded/

**Comment by craigtao** [comment]
In your release note, I only see the deprecation of mg_mkpipe(), but I don't see how to replace it, not even a hint at all,  
 our product is still using 7.10, using mg_mkpipe this implementation, do you think I should ask?

for example:
Your documentation is very unclear, IPv4 and IPv6 use the same array to store, and it doesn't explain how to use it, so for a novice like me, your documentation is a bit invaluable

**Comment by craigtao** [comment]
> @craigtao This is 1 year ago, please don't necropost. Please see our [documentation](https://mongoose.ws/documentation/), and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples). https://mongoose.ws/documentation/tutorials/core/multi-threaded/

thanks your reply!!

**Pull request merged**
