### PR TITLE
Added setting "listen_backlog" to change number of backlog listeners

### PR DESCRIPTION
**Pull request by lodle**
default is 5 on windows

[Review on Reviewable](https://reviewable.io/reviews/cesanta/mongoose/537)

### CODE REVIEW

**Comment by cpq** [comment]
In that case I'd just modify SOMAXCONN definition for Windows

**Comment by lodle** [comment]
Its part of a system header file, not good to redef it

**Comment by cpq** [comment]
SOMAXCONN defines the listening queue.
Did you experience some specific practical issue?

**Comment by cpq** [comment]
Closing this.

**Pull request closed without merging**
