### PR TITLE
Add missing range check in mg_get_http_header()

### PR DESCRIPTION
**Pull request by rojer**
h/t @BushraAloraini

Fixes https://github.com/cesanta/mongoose/issues/1135

### CODE REVIEW

**Comment by lnksz** [comment]
Isn't https://github.com/cesanta/mongoose/blob/86f391c70158a0ee553746e326bc996a3a39b4c0/src/mg_http_cgi.c#L359 also affected?

**Comment by mtimperley** [comment]
> Isn't
> https://github.com/cesanta/mongoose/blob/86f391c70158a0ee553746e326bc996a3a39b4c0/src/mg_http_cgi.c#L359
> also affected @cpq ?

@lnksz, did you get an answer to your question? After reviewing this commit, I have the same question.

**Comment by cpq** [comment]
@mtimperley current HEAD has CGI support removed, and HTTP codebase heavily refactored.
So, not affected.

**Comment by mtimperley** [comment]
Thanks @cpq that is good to know. I'm currently supporting v6.18 as the plan to move to v7.1 is still some months away. I'm thinking this check will do no harm, so I might as well put it in with the others. Do you agree?

**Comment by cpq** [comment]
That makes sense, @mtimperley , thank you.

**Pull request merged**
