### PR TITLE
fix mg_is_error logic wrong 

### PR DESCRIPTION
**Pull request by osDanielLee**
Delete n == 0 in mg_is_error, because if connect function return 0, stand for connect work well, mg_is_error should be false not the TRUE( n == 0), look it carefully and you will find delete n == 0 won't effect the value of nc->err according to different rc value and errno.

Of course, if you don't delete n == 0 code, it won't raise a error, but it just happened to be right.

---
This change is [Reviewable](https://reviewable.io/reviews/cesanta/mongoose/733)

### CODE REVIEW

**Comment by osDanielLee** [comment]
Sorry for the so many commit info, but it's for synchronous the master branch. Actually, I just change one line only.

**Comment by osDanielLee** [comment]
please handle it @alashkin

**Comment by alashkin** [comment]
Integrated in https://github.com/cesanta/mongoose/commit/499a7d6a37f6e8074b9e4a7a5cc8bfbb8ef75fd7

Thank you!

**Comment by osDanielLee** [comment]
I'm so wondering why you doesn't just accept my code? I couldn't see any difference between 499a7d6 and https://github.com/cesanta/mongoose/pull/733/commits/78444533bf0b468a3d691ef04fcd7847bfcce3d6. May you let me know the reason please?

**Comment by alashkin** [comment]
Hi @osDanielLee! 
Sure.
If you take a look to PR history of _this_ repo, you can see, that all of them are closed with comment "integrated in ...." 
The reason is technical: this repo contains _only_ amalgamated mongoose.[ch] & stuff, while in realty mongoose.c is a result of amalgamation of several files. So, in any case, I cannot merge PR right here, I have to move code to _the real source file_ and then `cesantabot` amalgamates sources and publishes this repo: look into commit history history of this repo - none of them made by humans directly, everything published by `cesantabot`.
So, for small PRs we tend to simplify workflow and just copy-n-paste changes to the real sources. If PR is big and complicated we deamalgamate PR (or ask contributor to do this - amalgamation tools are available here: https://github.com/cesanta/mongoose/tree/master/tools), put the changes to sources and commit them back.
If you worries that I didn't preserved you name, we can fix it. For this you have to agreed with Cesanta CLA (https://docs.cesanta.com/contributors_la.shtml) and I'll recommit the thing with your name (but again - I'll close your PR in any case, as I said it is impossible to commit directly to this repo)
Sorry for inconvenience and again - thank you for your contribution.

**Comment by osDanielLee** [comment]
Hi, @Alexander Alashkin , I've got the reason so don't be bothered about the commit things. We all want the repo and community to be better. Thanks for your kind explanation.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cesanta/mongoose","title":"cesanta/mongoose","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cesanta/mongoose"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alashkin in #733: Hi @osDanielLee! \r\nSure.\r\nIf you take a look to PR history of _this_ repo, you can see, that all of them are closed with comment \"integrated in ....\" \r\nThe reason is technical: this repo contains _only_ amalgamated mongoose.[ch] \u0026 stuff, while in realty mongoose.c is a result of amalgamation of several files. So, in any case, I cannot merge PR right here, I have to move code to _the real source file_ and then `cesantabot` amalgamates sources and publishes this repo: look into commit history history of this repo - none of them made by humans directly, everything published by `cesantabot`.\r\nSo, for small PRs we tend to simplify workflow and just copy-n-paste changes to the real sources. If PR is big and complicated we deamalgamate PR (or ask contributor to do this - amalgamation tools are available here: https://github.com/cesanta/mongoose/tree/master/tools), put the changes to sources and commit them back.\r\nIf you worries that I didn't preserved you name, we can fix it. For this you have to agreed with Cesanta CLA (https://docs.cesanta.com/contributors_la.shtml) and I'll recommit the thing with your name (but again - I'll close your PR in any case, as I said it is impossible to commit directly to this repo)\r\nSorry for inconvenience and again - thank you for your contribution. "}],"action":{"name":"View Pull Request","url":"https://github.com/cesanta/mongoose/pull/733#issuecomment-259899151"}}}

**Pull request closed without merging**
