### PR TITLE
Fix segmentation fault in mg_http_reverse_proxy #1065

### PR DESCRIPTION
**Pull request by dmundt**
Fix segmentation fault in mg_http_reverse_proxy() #1065

### CODE REVIEW

**Comment by anatolyborodin** [comment]
[mongoose.c](https://github.com/cesanta/mongoose/blob/master/mongoose.c) is a so called "amalgamated" library. I'm not really sure, if it's being updated automatically or manually during a release. Anyway, [src/mg_http.c](https://github.com/cesanta/mongoose/blob/master/src/mg_http.c) is the original source, and should be updated as well. See e.g. 3fc61a3edc6b45f1218b61a0a560bf0332d5532c

@cpq what is the right way?

**Comment by anatolyborodin** [comment]
The logic regarding `mg_http_get_proto_dat()/mg_http_create_proto_data()` was changed in e5910da300613f0b37fb73f66e5f8c7b96cbd6b9. `mg_http_get_proto_dat()` allocated the missing object before. I'm not sure if it's a right thing to do again (should a getter function allocate anything?)

https://github.com/cesanta/mongoose/commit/e5910da300613f0b37fb73f66e5f8c7b96cbd6b9?diff=unified#diff-e2958a0adcf1d38b24ce49505c902074R670-R672 allows (?) the pointer to be `NULL`.

https://github.com/cesanta/mongoose/commit/e5910da300613f0b37fb73f66e5f8c7b96cbd6b9?diff=unified#diff-e2958a0adcf1d38b24ce49505c902074R3071-R3072 here is an explicit `mg_http_create_proto_data()` call.

**Comment by mwm29** [comment]
It looks like the seg fault occurs on line 8124 of mongoose.c: `mg_http_get_proto_data(be)->reverse_proxy_data.linked_conn = nc;` `be`'s proto_data is `NULL`.

I agree that it doesn't make sense for a getter to allocate data. You could add a check before this line instead of in the getter function. However with the fix in this pr or the fix I proposed, the reverse_proxy example still doesn't work. It no longer seg faults but the request to the backend server just hangs indefinitely. Is anyone else seeing this behavior?

**Comment by cpq** [comment]
Please debug it - run with the hexdump turned on, compile with the debugging on, etc.

**Comment by mwm29** [comment]
I ran the reverse_proxy example and connected with http_client. Attached are the hexdumps from reverse_proxy (hexdump.txt) and from http_client (clienthex.txt).


[hexdump.txt](https://github.com/cesanta/mongoose/files/3997135/hexdump.txt)
[clienthex.txt](https://github.com/cesanta/mongoose/files/3997136/clienthex.txt)

**Comment by mwm29** [comment]
So it looks like reverse_proxy sees the GET on 8000, sends it on 8000, receives it on 8001, 8001 generates and sends a 200, the 200 response is received on 8000, but isn't forwarded back to the client.

**Comment by TianQingshuai** [comment]
You can find the fixes code [https://github.com/cesanta/mongoose/issues/1087](here)
It does work fine.

**Comment by cpq** [comment]
The reverse proxy example was rewritten, adopted for the latest release.
See https://github.com/cesanta/mongoose/tree/master/examples/http-reverse-proxy
Closing this.

**Pull request closed without merging**
