### PR TITLE
Fuzzer extension + suggestion for oss-fuzz integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Hi,

This PR extends the existing fuzzer with the purpose of integrating mongoose into the [oss-fuzz](https://github.com/google/oss-fuzz) project.  OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects and it would be nice to integrate mongoose as well. Essentially, OSS-Fuzz will perform the fuzzing for you in a continuous manner and then email you bug reports, coverage reports etc. All we need is a set of email addresses that will receive this information.

If you are happy to integrate into OSS-Fuzz then I would be happy too to continue extending the fuzzer. Please tell me here if you would like integrating into OSS-Fuzz: for convenience I have made a PR (https://github.com/google/oss-fuzz/pull/4648) on the OSS-Fuzz repo that does the integration in case you are happy with it.

### CODE REVIEW

**Comment by cpq** [comment]
Could you adopt it to the current master please?

**Comment by DavidKorczynski** [comment]
Fixed @cpq - could you also provide an email for OSS-Fuzz? Notice the email should be linked to a google account for watching details on the fuzzing (coverage/stack traces etc.)

**Comment by cpq** [comment]
Pushed https://github.com/cesanta/mongoose/commit/d1b8f9e01fd0cfdf987d542b8f9e06efcd894fa9 to add base64 and get_var tests - would that actually suffice?

To answer your question about the email address - support@cesanta.com

**Comment by DavidKorczynski** [comment]
Thanks for putting in the updates. I think we can stick with the fuzzer you have now, which should be good.

You can see in the OSS-Fuzz PR https://github.com/google/oss-fuzz/pull/4648 how to integrate with the service. The only steps necessary are create the `project.yaml`, `build.sh` and `Dockerfile` files, which you see in the PR.

We (Ada Logics) collaborate with the OSS-Fuzz team on getting well-known open source libraries into the service to help secure the security posture of these open source libraries. As such, my interest is from a perspective of securing important open source projects.

**Comment by cpq** [comment]
Fantastic, thank you David.

I presume I can close this now - let me know if anything required moving forward.

**Pull request closed without merging**
