### PR TITLE
Sort mime types and remove duplicates

### PR DESCRIPTION
**Pull request by jcorporation**
As the title says. CLA is already signed by me.

### CODE REVIEW

**Comment by cpq** [comment]
The list is intentionally unsorted: the most "popular" entries are at the top.
Please keep the original sorting, and retain only "duplicates" change.
Alternatively, a list could be sorted and a binary search can be employed instead of simple loop.

**Comment by jcorporation** [comment]
Ok, the commit now removes only a duplicate entry.

In my opinion the list is relatively arbitrary. My preferred list would be:
- css
- js
- webp
- png
- jpg
- jpeg 
- svg
- html
- htm
- shtml
- ico
- woff
- woff2
- pdf

This is a list of the most frequently used files extensions.

**Comment by cpq** [comment]
Using a shorter list sounds good.. How did you compile that short list?

**Comment by jcorporation** [comment]
In my experience this are the most used file types for serving a webpage. But looking at my webserver statistics I would move css and js after html. CSS and JS files are often combined to reduce the number of assets to serve. Eventually we can also remove woff, woff2 is widely established.

**Pull request closed without merging**
