### PR TITLE
<bug>: avoid realloc(xx, 0)

### PR DESCRIPTION
**Pull request by zuzy**
Call resize(buf, 0) by chance and get double freed....

### CODE REVIEW

**Comment by rojer** [comment]
as long as `realloc(xx, 0)` returns NULL in that case, it should be fine.
what is the compiler we are talking about?

**Comment by zuzy** [comment]
Ubuntu16.04, x86, gcc-5 for now.
I treat mongoose-mqtt as a way to transport files. Publish & on-message callback are called heavily.
Sometimes 'Double free' error occurs by accient, and I found that 'realloc 0' is somehow unclear in standard. 
As a result, 'double free' disappaerd after I did that.

**Comment by rojer** [comment]
ok, we'll need something more substantial. this code is well exercised in many scenarios and behaves correctly.
you can use ASAN to track down your double-free.

**Comment by cpq** [comment]
@zuzy please re-test with the current master.

**Comment by cpq** [comment]
Closing this until confirmed.

**Pull request closed without merging**
