### PR TITLE
Add wolfSSL support

### PR DESCRIPTION
**Pull request by julek-wolfssl**
- Added Makefile wolfSSL build option with `SSL=WOLFSSL`
- Fixed missing BIO symbol errors
- Rename `fe` to `mg_fe` as it collides with `fe` defined in `wolfssl/wolfcrypt/fe_operations.h`
- `byte` variable name shadows the wolfSSL `byte` type
-  Updated nightly to run wolfSSL tests

Tested with `make test`

### CODE REVIEW

**Comment by cpq** [comment]
@julek-wolfssl thank you! Please sign the CLA https://cesanta.com/cla.html and we'll have it integrated

**Comment by julek-wolfssl** [comment]
Hi @cpq, I signed the CLA and rebased the branch to fix merge conflicts.

Juliusz

**Comment by cpq** [comment]
@julek-wolfssl thank you, much appreciated!

**Comment by scaprile** [comment]
@julek-wolfssl 
Hello Juliusz, 
Github tests are failing, like something is missing at linkage.

I added the definition of `OPENSSL_IS_WOLFSSL` that was referred in the code but never defined
https://github.com/cesanta/mongoose/blob/cfb2a0f9c415f403cf4be91406aab5d2463dcde9/src/tls_openssl.h#L3-L7
and so created a TLS arch for WolfSSL:
https://github.com/cesanta/mongoose/blob/cfb2a0f9c415f403cf4be91406aab5d2463dcde9/src/tls.h#L6
allowed tls_openssl.[ch] to be include in both cases:
https://github.com/cesanta/mongoose/blob/cfb2a0f9c415f403cf4be91406aab5d2463dcde9/src/tls_openssl.c#L4
and changed the Makefile:
https://github.com/cesanta/mongoose/blob/cfb2a0f9c415f403cf4be91406aab5d2463dcde9/test/Makefile#L56-L60

My changes are on branch `wolf`.
We'll be removing tests for WolfSSL, so I suggest you work forking that branch that should still have the test script. The full test (nightly) can be manually run with some patience and attached to this branch to check before submitting.
Feel free to contact me for anything you might need.
Regards.

**Comment by julek-wolfssl** [comment]
Hi @scaprile,

`EXTERNAL_OPTS_OPENVPN` is crucial to build against wolfSSL so that the `options.h` header is included without needing to modify your sources. Please leave it in the Makefile.

`OPENSSL_IS_WOLFSSL` is normally defined in `wolfssl/openssl/opensslv.h`. With your definition of `MG_TLS_WOLFSSL`, I think it would be best to replace all checks for `OPENSSL_IS_WOLFSSL` with `MG_TLS == MG_TLS_WOLFSSL`. I agree that is the better approach.

Your remaining changes look good!

Juliusz

**Comment by scaprile** [comment]
Thanks @julek-wolfssl 
I dared to remove that because we are not building WolfSSL... those tests just link against OS shared libraries. Is it possible those do not include the OpenSSL compatibility layer and hence the linking failures ?

Once this is working I plan to add WolfSSL to our TLS tutorial, and then your comment will play a key role, as users will be actually building. The Makefile in test/ is just for testing purposes, so I would only have what is actually needed in there.

You are right, I'll push that change to this branch. Can you please check the build failures ?

**Comment by julek-wolfssl** [comment]
In wolfSSL, we require that `wolfssl/options.h` is included before any other headers are included. This is a building requirement not a linking one. For open source ports we added the `EXTERNAL_OPTS_OPENVPN` macro to force wolfSSL to include `wolfssl/options.h` internally and this way we don't need to touch any of your includes. But adding `-I/usr/local/include -I/usr/local/include/wolfssl` all the OpenSSL headers get substituted for wolfSSL headers.

Can you point me to the build failures? Or give me the steps? I'm not sure what you're referring to.

Juliusz

**Comment by scaprile** [comment]
OK.
Let's take any mess that I might have introduced out of the equation, and start from the beginning.
This is what happened after we merged your PR: 

Tests run on Ubuntu 22.04. As you've set them up, the test script will install libwolfssl-dev and call our test Makefile,  that will build our unit tests. Mongoose is another source file, and nothing else. No more source files. The object code links against a shared library with `-lwolfssl` just as it does with OpenSSL and (in Linux and Mac) with MbedTLS.
That attempt to link ends with lots of undefined references (build command at top of snapshot):

Screenshot from 2024-05-16 17-20-41

**Comment by julek-wolfssl** [comment]
wolfSSL when installed from `apt` will be installed with a prefix of just `/usr` instead of `/usr/local` when installed from source. When I supply an incorrect path I get a similar error output. A solution to handle both cases can be to use `pkg-config` to set the `WOLFSSL` prefix like this `WOLFSSL ?= $(shell pkg-config wolfssl --variable=prefix)`.

**Comment by scaprile** [comment]
Getting closer !
Building fine in MacOS (wolfssl--5.7.0), fails on a specific test of ours that also fails on MbedTLS and is apparenty related to TLS1.3 and one of our tests. We'll check this later.
In Ubuntu 22.04 (ibwolfssl-dev (5.2.0-2)), we have `SSL_set1_host()` missing:
```
gcc mongoose.c unit_test.c packed_fs.c -O3 -g3 -fsanitize=address,undefined,alignment -fno-sanitize-recover=all -fno-omit-frame-pointer -fno-common -Wmissing-prototypes -Wstrict-prototypes -pedantic -W -Wall -Werror -Wshadow -Wdouble-promotion -fno-common -Wconversion -Wundef -Isrc -I. -DMG_MAX_HTTP_HEADERS=7 -DMG_ENABLE_LINES -DMG_ENABLE_PACKED_FS=1 -DMG_ENABLE_SSI=1 -DMG_ENABLE_ASSERT=1 -DMG_ENABLE_IPV6=0 -DMG_ENABLE_POLL=0 -DMG_ENABLE_EPOLL=1 -pthread -DMG_TLS=MG_TLS_WOLFSSL -DEXTERNAL_OPTS_OPENVPN -I/usr/include -I/usr/include/wolfssl -L/usr/lib -lwolfssl -o unit_test
src/tls_openssl.c: In function ‘mg_tls_init’:
src/tls_openssl.c:172:5: error: implicit declaration of function ‘SSL_set1_host’; did you mean ‘SSL_get_hit’? [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make: *** [Makefile:126: test] Error 1
```
Can you provide a workaround for this ?

**Comment by julek-wolfssl** [comment]
That API should definitely be present. It was added in 2022. Can you share which version of wolfSSL you are using?

**Comment by scaprile** [comment]
> In Ubuntu 22.04 (ibwolfssl-dev (5.2.0-2))

**Comment by scaprile** [comment]
Great, we build now !
I get this failure:
```
97219c9 3 net.c:174:mg_connect          5 -1 https://cesanta.com
97219c9 3 sock.c:140:mg_send            2 4 0:0:0 29 err 0
97219c9 3 tls_openssl.c:113:mg_tls_init 5 Setting TLS
97219ca 3 tls_openssl.c:199:mg_tls_init 5 SSL client OK
97219cf 3 sock.c:294:read_conn          2 4 0:0:0 45 err 0
97219cf 3 dns.c:168:dns_cb              5 cesanta.com is 148.251.54.236
97219cf 3 sock.c:385:mg_connect_resolve 5 5 -> 148.251.54.236:443 pend
9721be3 3 sock.c:294:read_conn          5 5 48:0:0 -2 err 0
9721be3 1 tls_openssl.c:9:tls_err_cb    5 wolfSSL error occurred, error = 188 line:11112 file:src/internal.
9721be3 1 tls_openssl.c:9:tls_err_cb    5 wolfSSL error occurred, error = 188 line:17428 file:src/internal.
9721be3 1 tls_openssl.c:9:tls_err_cb    5 wolfSSL error occurred, error = 188 line:8677 file:src/tls13.
9721be4 1 event.c:31:mg_error           5 5 tls hs: rc -1, err -188
9721be4 3 sock.c:294:read_conn          5 5 48:0:159 -2 err 0
9721be4 3 net.c:148:mg_close_conn       5 5 closed
9721be4 2 unit_test.c:1303:test_http_cl OK: 777
FAILURE unit_test.c:1304: ok == 200
```
If this can be easily solved, I'll go ahead and do it. Otherwise, at this time, I would disregard Ubuntu version and demand a newer release be manually built.

**Comment by julek-wolfssl** [comment]
Error `-188` indicates that the appropriate CA was not loaded and the certificate could not be verified. Either the CA needs to be loaded or `SSL_VERIFY_NONE` needs to be explicitly set as the verify option. Newer versions of wolfSSL have the option to define `OPENSSL_COMPATIBLE_DEFAULTS` when configuring wolfSSL. This define brings the defaults closer to OpenSSL like disabling verification by default.

**Comment by scaprile** [comment]
Cool, we skip that test for MbedTLS for similar reasons. Skipping it also on `(MG_TLS != MG_TLS_WOLFSSL || defined(OPENSSL_COMPATIBLE_DEFAULTS))`

Linux tests now pass. Thanks for your help !

**Pull request merged**
