### PR TITLE
Fix unit test under (actual) Windows

### PR DESCRIPTION
**Pull request by scaprile**
#1605

### CODE REVIEW

**Comment by cpq** [comment]
I don't like this fix.
It changes a source file under us, it just should be done like this.

Is the underlying issue with Git changing line endings on windows?
Then, maybe we can use another file to test against, not version.h - maybe some generated binary file, which is not touched by Git.

**Comment by scaprile** [comment]
Agreed, I didn't like this either but I tried to insert a `\r` instead and it broke on our tests (I think because git actually works on Linux, only the test works on wine).
Yes, I also think a binary file is the proper solution, we could try to register the version file as "binary" (-b in CVS...) so it is not changed by git clients, but a specific binary file will be future proof and less human error prone.
I'll change this on Monday

**Comment by cpq** [comment]
Yeah, we can make some dummy file in the test/.. dir - or use an existing one, which Git does not mess up with

**Comment by scaprile** [comment]
The whole point of the test is to check rewrites: 2392 -> `opts.root_dir = "./test/data,/foo=./src";`
The test in line 2406 should also fail as git should also be modifying a.txt unless it has been marked as binary somehow...
The failing test in line 2408 intentionally tries to fetch from src to test rewriting.
https://github.com/cesanta/mongoose/blob/f68d83dbf065b07d1d7b5c222562b52a705a6e3e/test/unit_test.c#L2387-L2414

**Comment by scaprile** [comment]
Exactly.
The whole Makefile does not expect to be run under Windows, neither do unit tests. Manually trimming the build process and running on Windows fails on line 2406 as expected; perhaps in many other places.

**Pull request closed without merging**
