### PR TITLE
Add example Dockerfile to build and run http-server

### PR DESCRIPTION
**Pull request by scaprile**

### CODE REVIEW

**Comment by cpq** [comment]
Thanks Sergio!
Is this Dockerfile used by something, like, a tutorial?

**Comment by scaprile** [comment]
> Thanks Sergio! Is this Dockerfile used by something, like, a tutorial?

No, but we could add it to the HTTP server tutorial, what do you think ?

**Comment by cpq** [comment]
@scaprile to be honest, I think docker would be an overkill..

I think we should also kill all docker usage for ARM builds, and rely on ARM GCC installed

**Comment by scaprile** [comment]
Moving to the chat...

**Pull request closed without merging**
