### PR TITLE
LWIP SO_REUSEADDR & ESP32 logging

### PR DESCRIPTION
**Pull request by dexterbg**
The LWIP commit checks for the LWIP SO_REUSE build option to decide wether to include the setsockop call. This solves the issue of lost connections blocking server ports due to sockets remaining in TIME_WAIT.

The ESP32 logging commits change the stderr logging channel to the ESP-IDF standard syslog channel on an ESP32 platform, so mongoose log output is consistent & cooperative with other log output and can be controlled by the ESP log level. File logging and the mongoose log control & filters can still be used, only the stderr channel is changed.

The debug log on mg_socket_if_destroy_conn() enables tracing socket close behaviour and timing.

These changes have been done for and tested within our ESP32 project (OVMS V3).

Tell me if you need separate pull requests.

Regards,
Michael

### CODE REVIEW

**Comment by cpq** [comment]
@rojer shall we integrate this?

**Comment by cpq** [comment]
Thank you.
Prior to integrating this, please confirm you've signed the CLA, linked from 
https://github.com/cesanta/mongoose#contributions

**Comment by dexterbg** [comment]
I signed the CLA before creating the original pull request. @slcasner Steve, how about you?

**Comment by slcasner** [comment]
I have signed the CLA now.

**Comment by awong-dev** [comment]
Any chance some version of this could be updated and merged?  I am having similar issues and would like to remove my local workarounds for MG_CTL_MSG_MESSAGE_SIZE being too large for an esp32.

**Comment by cpq** [comment]
This PR contains several unrelated pieces - please split, one PR per single functionality piece. The PR should be against the `dev` branch, and one PR must have only one commit.

**Comment by markwj** [comment]
> This PR contains several unrelated pieces - please split, one PR per single functionality piece. The PR should be against the dev branch, and one PR must have only one commit.

Is there any point? There are 33 outstanding pull requests here, dating back to 5 years to 2015. Only three have any response, and this one has sat dead since October 2018. It seems Cesanta is simply not interested in community improvements? We could go to the work to re-factor all these improvements and bug fixes into individual PRs, but there seems little point unless they get some attention.

**Comment by cpq** [comment]
We've been bad lately about the submitted contributions - apologies about that, we'll be more responsive.

**Comment by cpq** [comment]
Thanks.
Closing this, as the latest codebase enables SO_REUSEADDR on ESP32 by default.
Please reopen if required.

**Pull request closed without merging**
