### PR TITLE
Display decoded uri in list_dir

### PR DESCRIPTION
**Pull request by jcorporation**
Display the url decoded path in title

### CODE REVIEW

**Comment by jcorporation** [comment]
Sorry, but I can not find any error...

**Comment by cpq** [comment]
```sh
$ make vc98
```

Fails, cause your change is not ISO C89 compliant.
Regardless, what is the issue with the current code?

**Comment by jcorporation** [comment]
The uri displayed in the title of the dir listing is not url decoded

**Comment by cpq** [comment]
Well.. So what?

**Comment by jcorporation** [comment]
It is a cosmetic issue. The user sees the url encoded uri and not the better readable decoded uri in the page title and in the h1 tag.

**Comment by cpq** [comment]
I understand that.
Could you provide a real life example, e.g. a simple directory tree that demonstrates an issue, please?

**Comment by jcorporation** [comment]
Sure:
Path is: /Alben/Marilyn_Manson/Holy_Wood_(In_The_Shadow_Of_The_Valley_Of_Death)/

- In the directory listing of `/Alben/Marilyn_Manson/` the subdirectory name is displayed correctly as `Holy_Wood_(In_The_Shadow_Of_The_Valley_Of_Death)/`
- Changing in this directory displays in the header: `Index of /Alben/Marilyn_Manson/Holy_Wood_%28In_The_Shadow_Of_The_Valley_Of_Death%29/`

**Pull request closed without merging**
